# Numpy

Python Numérico: **numpy**

NumPy é um módulo para a linguagem de programação Python, que suporta o processamento de grandes, multi-dimensionais arranjos e matrizes, juntamente com uma grande coleção de funções matemáticas de alto nível para operar sobre estas matrizes.

Útil para grande quantidades de dados e operações, já que a operação de listas em python não são otimizados em python e o módulo numpy é.

Essa módulo é eficiente para a minimização do processamento, pois o móduo utilizado uma estrutra em 'c' para a execução das funções e métodos.

## Instalando e Importando o Módulo Numpy

In [3]:
# instalação do pacote/bibioteca numpy pela máquina virtual Linux
! pip install numpy                    
# importando o módulo numpy
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Criando Arrays com Numpy

In [30]:
import numpy as np

# Array no formato lista --> conrtido para classe 'numpy.ndarray'
# Criando um array uni-dimensional (1D)
# A classe que esse array pertence é 'numpy.ndarray'
# Observe que ao contrário das listas, não temos virgulas separando os elementos.

print('Dimensão 1D')
arr1D = np.array([1,2,3,4]) 
print(arr1D, type(arr1D))

# Array no formato tupla --> conrtido para classe 'numpy.ndarray'
# A classe que esse array pertence é 'numpy.ndarray', perceba que a classe não muda mesmo que passamos uma tupla.

arr1D = np.array((1,2,3,4)) 
print(arr1D, type(arr1D))

Dimensão 1D
[1 2 3 4] <class 'numpy.ndarray'>
[1 2 3 4] <class 'numpy.ndarray'>


In [56]:
import numpy as np

# Criando um array bi-dimensional (2D)
# Como argumento recebemos listas e tuplas separadas por vírgulas. 
# Deve-se delimitar essas listas com colchetes ou parênteses.

print('Dimensão 2D')
arr2D = np.array([[1,2,3], (5,6,7)]) 
print(arr2D, type(arr2D))
print()

# Criando um array tri-dimensional (3D)
# Obedece a mesma ideia das dimensões anteriores já apresentadas.
print('Dimensão 3D')
arr3D = np.array([[(1,2,3),(4,5,6)], [(7,8,9),(10,11,12)]]) 
print(arr3D, type(arr3D))
print()

# Criando um array de dimensão-zero (0D)
# Como argumento deve-se passar apenas um valor, não sendo uma coleção.
print('Dimensão 0D')
arr0D = np.array(3.1316)
print(arr0D)


print()
''' RESUMO FINAL DAS DIMENSÕES DE UM ARRAY - Pode-se fazer uma associação:

    1D - Corresponde ao acesso de uma letra em uma linha.
    2D - Corresponde ao acesso de de uma linha em uma página e a letra dessa linha. 
    3D - Corresponde ao acesso de uma págiana de um livro, posteriomente de uma linha desse livro, e de uma letra dessa linha.
    4D - Corresponde ao acesso de um livro, posteriormente a página desse livro, depois a linha e a letra dessa linha.

    ... e assim seguimos para mais dimensões!

'''

Dimensão 2D
[[1 2 3]
 [5 6 7]] <class 'numpy.ndarray'>

Dimensão 3D
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'>

Dimensão 0D
3.1316



' RESUMO FINAL DAS DIMENSÕES DE UM ARRAY - Pode-se fazer uma associação:\n\n    1D - Corresponde ao acesso de uma letra em uma linha.\n    2D - Corresponde ao acesso de de uma linha em uma página e a letra dessa linha. \n    3D - Corresponde ao acesso de uma págiana de um livro, posteriomente de uma linha desse livro, e de uma letra dessa linha.\n    4D - Corresponde ao acesso de um livro, posteriormente a página desse livro, depois a linha e a letra dessa linha.\n\n    ... e assim seguimos para mais dimensões!\n\n'

## Checando o Número de Dimensões e a Forma de um Array 

In [1]:
import numpy as np

arr0D = np.array(123)
arr1D = np.array([1,2,3])
arr2D =  np.array([[1,2,3], [3,5,6]]) 
arr3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) 

# O atributo ndim retorna a dimensão de um array.
print('Dimensão dos arrays:')
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

# O atributo 'shape' retorna a forma do array através de uma tupla. 
print('Forma dos arrays')
print(arr0D.shape, type(arr3D))     # como o array não é composto por uma coleção de dados, então o retorno será uma tupla vazia
print(arr1D.shape, type(arr3D))     # irá retornar uma tupla com um único elemento, informando o número de elementos presentes no array 1D. Número de colunas.
print(arr2D.shape, type(arr3D))     # irá retornar uma tupla com dois elementos. Primeiro elemento informa o número de linhas, e o segundo o número de colunas.
print(arr3D.shape, type(arr3D))     # irá retornar uma tupla com três elementos. Primeiro elemento informa o número de matrizes, o segundo as linhas, e o terceiro as colunas.

Dimensão dos arrays:
0
1
2
3
Forma dos arrays
() <class 'numpy.ndarray'>
(3,) <class 'numpy.ndarray'>
(2, 3) <class 'numpy.ndarray'>
(2, 2, 3) <class 'numpy.ndarray'>


## Criando um Array com N-dimensões

É possível gerar um array de N-dimensões, basta passar um segundo argumento **ndim = n** para o método o método **np.array**. Nessa situação **n** informa a dimensão.  

A esse array podemos associar os correspondentes elementos da tupla,  obtida pelo atributo shape, da seguinte forma (ex: array em 5D):

1. - Primeiro índice da tupla informa o número de prateleiras da estante.
2. - Segundo índice da tupla informa o número de livros na correspondente prateleira.
3. - Terceiro índice da tupla informa o número de páginas contidas no livro.
4. - Quarto índice da tupla informa o número de linhas presentes na página.
5. - Quinto índice da tupla informa o número de elementos numa linha.  

In [6]:
import numpy as np

# segundo argumento ndim=5 cria um array de dimensão 5
arr5D = np.array([1,2,3,4,5], ndmin = 5)

print('Array: ',arr5D)
print('Dimensão: ',arr5D.ndim)
print('Forma: ',arr5D.shape)

Array:  [[[[[1 2 3 4 5]]]]]
Dimensão:  5
Forma:  (1, 1, 1, 1, 5)


## Acessando Elementos de Um Arranjo

In [8]:
import numpy as np


# Definindo um arranjo 1D
arr1D = np.array([1,2,3,4]) 

# Acessando os elementos de um arranjo 1D
print('Acessando elementos array 1D:')
print(arr1D[0],arr1D[1],arr1D[2],arr1D[3])
print('Fazendo operações com elementos de um array 1D:')
print(arr1D[0]*arr1D[3])

print()

# Definindo um arranjo 2D
arr2D = np.array([[1,2,3], [4,5,6]])
# Acessando os elementos de um arranjo 2D
print('Acessando elementos array 1D:')
print(arr2D[0,0],arr2D[0,1],arr2D[0,2])
print(arr2D[1,0],arr2D[1,1],arr2D[1,2]) 


print()

# Definindo um arranjo 3D
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
# Acessando os elementos de um arranjo 2D
print('Acessando elementos array 3D:')
print(arr3D[0,0,0],arr3D[0,0,1],arr3D[0,0,2])
print(arr3D[0,1,0],arr3D[0,1,1],arr3D[0,1,2])
print(arr3D[1,0,0],arr3D[1,0,1],arr3D[1,0,2])
print(arr3D[1,1,0],arr3D[1,1,1],arr3D[1,1,2])


print()

# O acesso dos elementos também pode ser com o uso dos números negativos.
# Similar a como acessavamos os últimos elementos de uma lista.

# Definindo um arranjo 2D
arr2D = np.array([[1,2,3], [4,5,6]])
# Acessando os elementos de um arranjo 2D
print('Acessando elementos com índices negativos em um array 2D:')
print(arr2D[0,-1],arr2D[0,-2],arr2D[0,-3])
print(arr2D[1,-1],arr2D[1,-2],arr2D[1,-3]) 

Acessando elementos array 1D:
1 2 3 4
Fazendo operações com elementos de um array 1D:
4

Acessando elementos array 1D:
1 2 3
4 5 6

Acessando elementos array 3D:
1 2 3
4 5 6
7 8 9
10 11 12

Acessando elementos com índices negativos em um array 2D:
3 2 1
6 5 4


## Fatiamento de Arrays

In [16]:
# seja um array 1D
arr1D = np.array([1,2,3,4,5,6,7])

# podemos fazer a operação de fatiamento.
# sempara os elementos de um array de forma ordenada em seus índices.
# mesma operação que fizemos com as listas.


print(arr1D[2:6])
# [1  2  3  4  5  6  7]
# [1  2| 3  4  5  6| 7] =  [3  4  5  6]
print(arr1D[1:5])
# [1  2  3  4  5  6  7]
# [1| 2  3  4  5| 6  7] =  [2  3  4  5]
print(arr1D[:5])
# [1  2  3  4  5  6  7]
# [1  2  3  4  5| 6  7] = [1  2  3  4  5]
print(arr1D[5:])
# [1  2  3  4  5  6  7]
# [1  2  3  4  5 |6  7] = [6 7]


print()

# FATIAMENTO JUNTO COM OS ÍNDICES NEGATIVOS

print('Fatiamento com índices negativos: ')
print(arr1D[-3:-1])
# [1  2  3  4  5  6  7]
# [1| 2  3  4 |5  6 |7] =  [5  6]
print(arr1D[-6:-1])
# [1  2  3  4  5  6  7]
# [1| 2  3  4  5  6| 7] =  [2  3  4  5  6  7]
print(arr1D[-6:])
# [1  2  3  4  5  6  7]
# [1| 2  3  4  5  6  7|] =  [2  3  4  5  6  7]
print(arr1D[:-6])
# [1  2  3  4  5  6  7]
# [1| 2  3  4  5  6  7] =  [1]

print()

# FATIAMENTO EM PASSOS
# É necessário passar mais um argumento
print('Fatiamento em passos: ')
print(arr1D[1:6:2])
# [1  2  3  4  5  6  7]
# [1| 2  3  4  5  6 |7] =  [2  4  6]
print(arr1D[::2])
# [1  2  3  4  5  6  7]
# [1  2  3  4  5  6  7] =  [1  3  5  7]
print(arr1D[-5:-1:2])
# [1  2  3  4  5  6  7]
# [1  2  3  4  5  6  7] =  [3 5]

[3 4 5 6]
[2 3 4 5]
[1 2 3 4 5]
[6 7]

Fatiamento com índices negativos: 
[5 6]
[2 3 4 5 6]
[2 3 4 5 6 7]
[1]

Fatiamento em passos: 
[2 4 6]
[1 3 5 7]
[3 5]


In [26]:
# FATIAMENTO EM ARRAYS DE 2 DIMENSÕES

# Definindo um arranjo 2D
arr2D = np.array([[1,2,3], [4,5,6]])


print(arr2D[0,0:2])
# [[1  2  3]  [4  5  6]]
#  [1 |2  3|] = [1,2]
print(arr2D[0,1:3])
# [[1  2  3]  [4  5  6]]
#  [1 |2  3|] = [2,3]
print(arr2D[1,2:3])
# [[1  2  3]  [4  5  6]]
#  [4  5 |6|] = [6]
print(arr2D[1,:-1])
# [[1  2  3]  [4  5  6]]
#  [4  5 |6] = [4 5]

[1 2]
[2 3]
[6]
[4 5]


## Método **.copy( )** e método **.view(  )**

In [35]:
import numpy as np

# Seja um array 1D
arr1D = np.array([1,2,3,4,5,6])

# método .copy()
# copia o array 1D arr1D para x
x = arr1D.copy()

arr1D[0] = -111

# Nesse método o array copiado é independente do array que passou a copia
# Os identificadores não referenciam o mesmo objeto
# O arranjo original não é alterado ao modificar os elementos do array 1D
print(arr1D)
print(x)

print()

# Observação: 'x' é proprietário dos dados! Ele não aponta para algo.
# Com o atributo .base deveria retorna None, então deve ser proprietário
print(arr1D.base)
print(x.base)

[-111    2    3    4    5    6]
[1 2 3 4 5 6]

None
None


In [34]:
import numpy as np

# Seja um array 1D
arr1D = np.array([1,2,3,4,5,6])

# método .copy()
# copia o array 1D arr1D para x
x = arr1D.view()

x[0] = -111

# Nesse método o array copiado depende do array que passou a copia
# Os identificadores referenciam o mesmo objeto
# O arranjo original é alterado ao modificar os elementos do array 1D
print(arr1D)
print(x)

print()

# Observação: 'x' não é proprietário dos dados! Ele apenas aponta.
# Com o atributo .base deveria retornar None para ser proprietário
print(arr1D.base)
print(x.base)


[-111    2    3    4    5    6]
[-111    2    3    4    5    6]

None
[-111    2    3    4    5    6]


## Método **.reshape()**

In [43]:
# Este método permite alterar a forma de um array. 
# Por exemplo, pode-se transformar um arranjo 1D em um 2D.

# Definindo o array e sua forma
arr1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1D, '\n', arr1D.shape)

print()

# Nessa situação o primeiro argumento do método reshape corresponde as linhas.
# O segundo elemento corresponde as colunas.
print('TRANSFORMA 1D -> 2D')
newarr = arr1D.reshape(3,4)
print('novo array: ', newarr) 
print('dimensão novo array: ', newarr.ndim)
print('nova forma: ', newarr.shape)

# Podemos transformar o array 1D -> 3D
# Situação com 2 linhas de 3 colunas
print('TRANSFORMA 1D -> 3D')
newarr = arr1D.reshape(2,2,3)
print('novo array: ', newarr) 
print('dimensão novo array: ', newarr.ndim)
print('nova forma: ', newarr.shape)

print()

# Situação com 3 linhas e 2 colunas
print('TRANSFORMA 1D -> 3D')
newarr = arr1D.reshape(2,3,2)
print('novo array: ', newarr) 
print('dimensão novo array: ', newarr.ndim)
print('nova forma: ', newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 (12,)

TRANSFORMA 1D -> 2D
novo array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dimensão novo array:  2
nova forma:  (3, 4)
TRANSFORMA 1D -> 3D
novo array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimensão novo array:  3
nova forma:  (2, 2, 3)

TRANSFORMA 1D -> 3D
novo array:  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimensão novo array:  3
nova forma:  (2, 3, 2)


In [50]:
# ACHATAMENTO DE UM ARRAY - Achatamento 
# Podemos diminuir a dimensão de um arranjo: nD -> 1D

import numpy as np

# definindo um array
arrnD = np.array([[[1,2,3],[4,5,6]]])

# através do índice -1 no argumento estamos informando para o arranjo 2D => 1D
newarr = arrnD.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Interando Elementos de Um Array 

In [57]:
import numpy as np

# Definindo os arrays com n-D
arr1D = np.array([1,2,3,4,5,6,7])
arr2D = np.array([[1,2,3], (5,6,7)]) 
arr3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) 


# Interando os elementos de do arr1D
print('Interando os elementos de arr1D:')
print(arr1D, '\n')
for coluna in arr1D:
  print(coluna)

print()

# Interando os elementos de do arr2D
print('Interando os elementos de arr2D:')
print(arr2D, '\n')
for linha in arr2D:
  for coluna in linha:
    print(coluna)

print()

# Interando os elementos de do arr3D
print('Interando os elementos de arr3D:')
print(arr3D, '\n')
for matriz in arr3D:
  for linha in matriz:
    for coluna in linha:
      print(coluna)

Interando os elementos de arr1D:
[1 2 3 4 5 6 7] 

1
2
3
4
5
6
7

Interando os elementos de arr2D:
[[1 2 3]
 [5 6 7]] 

1
2
3
5
6
7

Interando os elementos de arr3D:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

1
2
3
4
5
6
7
8
9
10
11
12


## Interando com o métdo **.ndinter(  )**

In [59]:
# UTILIZANDO A FUNÇÃO .ndinter() também é possível interar o array.
# Muito útil de interar quando a dimensão do array é muito grande.

import numpy as np

arr3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) 
print(arr3D, '\n')

for coluna in np.nditer(arr3D):
  print(coluna)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

1
2
3
4
5
6
7
8
9
10
11
12


### Interando com o método **.ndenumerate()**

In [62]:
# UTILIZANDO A FUNÇÃO .ndenumerate() também é possível interar o array.
# Retorna uma tupla, onde o primeimeiro elemento informa o índice de cada elemento interado.
# O segundo elemento é o valor interado do array.

import numpy as np

arr3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) 
print(arr3D, '\n')

for coluna in np.ndenumerate(arr3D):
  print(coluna)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((1, 0, 0), 7)
((1, 0, 1), 8)
((1, 0, 2), 9)
((1, 1, 0), 10)
((1, 1, 1), 11)
((1, 1, 2), 12)


## Juntando arrays


In [65]:
import numpy as np

# Podemos juntar os arranjos por concatenação
# Deve-se usar a função .concatenate
# Os argumentos passados são os arrays que queremos juntar na forma de tupla

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [67]:
import numpy as np

# Podemos juntar os arranjos pela função .stack( (arr1,arr2), axis = ... )
# Primeiro argumento corresponde a uma tupla, onde os elementos são os arranjos que serão empilhados.
# O eixo defini como os arranjos serão juntados:
#                 axis = 0 (a cada novo array uma nova linha é gerada)
#                 axis = 1 (junta as colunas de índice e gera uma nova linha)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print('axis = 0')
arr = np.stack((arr1,arr2),axis = 0)
print(arr)

print()

print('axis = 1')
arr = np.stack((arr1,arr2),axis = 1)
print(arr)


axis = 0
[[1 2 3]
 [4 5 6]]

axis = 1
[[1 4]
 [2 5]
 [3 6]]


In [71]:
import numpy as np

# Podemos juntar os arranjos pela função .hstack( (arr1,arr2, ...))
# Similar a função .concatenate() 
# Recebe um único argumento, sendo uma tupla, onde os elementos são os arrays.
# obs: hstack pode ser entendido como 'h' de horizontal

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print('Função .hstack()')
arr = np.hstack((arr1,arr2))
print(arr)

print()


# Podemos juntar os arranjos pela função .hstack( (arr1,arr2, ...)) empilhando eles.
# Similar a função .stack() na condição em que axis = 0
# obs: vstack pode ser entendido como 'v' de vertical
# Recebe um único argumento, sendo uma tupla, onde os elementos são os arrays.


print('axis = 1')
arr = np.vstack((arr1,arr2))  
print(arr)


Função .hstack()
[1 2 3 4 5 6]

axis = 1
[[1 2 3]
 [4 5 6]]


## Separando arrays


In [76]:
import numpy as np

# Podemos separa um array com a função/método .array_split()
# A função recebe 2 argumentos:
# O primeiro argumento é o array que desejamos separar ou dividir.
# O segundo argumento é quantidade que desejamos dividir o array.

arr = np.array([1,2,3,5,6])

# Dividindo o array 1D em três partes.
print('Dividindo o array em três partes:')
newarr = np.array_split(arr,3)
print(newarr)

print()

# Dividindo o array 1D em quatro partes.
print('Dividindo o array em quatro partes:')
newarr = np.array_split(arr,4)
print(newarr)


Dividindo o array em três partes:
[array([1, 2]), array([3, 5]), array([6])]

Dividindo o array em quatro partes:
[array([1, 2]), array([3]), array([5]), array([6])]


In [79]:
# Dividindo um array 2D

#Dividindo um array 2D de 2 linhas em 2 partes
arr = np.array([[1,2,3],[4,5,6]])
newarr = np.array_split(arr,2)
print(newarr)

#Dividindo um array 2D de 2 linhas em 3 partes
# Obs: nessa situação um array nulo é gerado
arr = np.array([[1,2,3],[4,5,6]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [ ]:
# A função .split() ainda admite um terceiro argumento, mas deixaremos pra estudar isso outra hora.

## Pesquisa por Elementos Em um Arranjo

In [88]:
import numpy as np

# Definindo o arranjo arr.
arr = np.array([10,20,30,40,10,20,30,40,10,20,30,40])

# Podemos pesquisar os elementos de um arranjo através da função/mulo .where()
# Essa função recebe como argumento o elemento que desejamos procurar junto com o próprio array e o operador de comparação.
# Ela retorna um array especificando os índices em que o elementos passado como argumento é igual.

# [10,20,30,40,10,20,30,40,10,20,30,40]
#  0,  1, 2, 3, 4, 5, 6, 7, 8, 9,10,11   
x = np.where(arr == 40)
print(x)

print()

arr = np.array([1,2,3,4,5,6,7,8,9,10])
# Pesquisando os índices pares e impares
print('Par: ')
par = np.where(arr%2 == 0)
print(par)
print('Imapar: ')
impar = np.where( arr % 2 == 1)
print(impar)

(array([ 3,  7, 11]),)

Par: 
(array([1, 3, 5, 7, 9]),)
Imapar: 
(array([0, 2, 4, 6, 8]),)


In [95]:
import numpy as np

# Definindo o arranjo arr.
arr = np.array([6,7,8,9])

# A função/método .searchsorted() pesquisa um item e retorna um índice conforme a regra:
#    arr[i-1] < valor <= arr[i+1]       --  Definida como default, mesmo que side = 'left'
#    arr[i-1] <= valor < arr[i+1]       --  side = right 

# Esse método recebo como primeiro argumento o array.
# O segundo argumento é o 'valor' que estamos impondo para satisfazer a regra acima.
# O terceiro argumento é o side, e define como iremos respeitar a regra acima.

x = np.searchsorted(arr, 8)
print('side left:',x)
y = np.searchsorted(arr, 8, side = 'right')
print('side right:',y)

# Função útil para fazer o ordenamento de um array.

side left: 2
side right: 3


## Ordenamento de arrays

In [100]:
import numpy as np

# O ordenamento de arranjos é feito com o método/função .sort()

arr = np.array([6,3,7,1,2,12,4]) 
print(np.sort(arr))                    # ordenamento numérico

arr = np.array(['A','K','C','B','Z','M','L']) 
print(np.sort(arr))                    # ordenamento alfabético

arr = np.array([True, True, False, False, True])
print(np.sort(arr))                    # ordenamento booleano

arr = np.array([[4,2,1],[5,1,10]])
print(np.sort(arr))                     # ordenamento em um array bi-dimensional


[ 1  2  3  4  6  7 12]
['A' 'B' 'C' 'K' 'L' 'M' 'Z']
[False False  True  True  True]
[[ 1  2  4]
 [ 1  5 10]]


## Filtrando Arranjos

In [105]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])
print('array antigo: ',arr)

x = [True, True, False, False, False, True, True, True]
print(x)

# inserindo os elementos booleanos da lista 'x' podemos informar quais índices aparecem no array newarr  
newarr = arr[x]
print('novo array: ',newarr)

array antigo:  [10 20 30 40 50 60 70 80]
[True, True, False, False, False, True, True, True]
novo array:  [10 20 60 70 80]


In [106]:
import numpy as np

# criando um filtro que retorne um array apenas com os valores maiores que 40

# Definindo o array
arr = np.array([10,20,30,40,50,60,70,80])

# Criano a lista responsável por fazer o filtro
filtro = []

for x in arr:
  if x > 40:
    filtro.append(True)
  else:
    filtro.append(False)

newarr = arr[filtro]

print('array antigo:', arr)
print('filtro:', filtro)
print('array novo:', newarr)


array antigo: [10 20 30 40 50 60 70 80]
filtro: [False, False, False, False, True, True, True, True]
array novo: [50 60 70 80]


In [108]:
# Criando um filtro diretamente de um array que retorna os valores maiores que 40
# Forma mais simples que a do explo acima

import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])
filtro = arr > 40
print(filtro)

newarr = arr[filtro]
print(newarr)

[False False False False  True  True  True  True]
[50 60 70 80]


## Números Pseudo-Randômicos

Um gerador de número pseudo-aleatório é um algoritmo normalmente derivado de uma função matemática que gera uma seqüência de números, os quais são aproximadamente independentes um dos outros.

In [136]:
# Em geral o numpy é um módulo.  Os métodos utilizados até então foram todos retirados do mesmo módulo.
# No então, o módulo numpy é ainda mais amplo, sendo composto por um conjunto de módulo (O QUE FORMA UMA BIBLIOTECA)
# Um dos módulos presentes é o módulo random

from numpy import random

# gera um número aleatório interio entre 0 e 99
# os argumentos são o que definem o intervalo 
print('número inteiro aleatório:')
x = random.randint(100) 
print(x)
x = random.randint(0,10)
print(x)

print()

# podemos gerar valores reais
# gera-se um número entre zero e um. 
# Esse é o único intervalor permitido.
print('número real aleatório:')
x = random.rand() 
print(x)

# Se quisermos gerar valores aleatórios reais fora desse intervalo, é necessário fazer uma multiplicação
x = random.rand()*100   # 100 é o intervalo limite 
print(x)

print()

# gerando um array 1D de números pseudo-randômicos inteiros
# primeiro argumento continua sendo o intervalo onde se gera os números aleatórios
# deve-se passar um segundo argumento size = ..., onde ... informa o tamanho do array (constitue uma tupla 1D)
x = random.randint(100, size=(10))
print(x)

print()

print('Número aleatório inteiro 2D')
# gerando um array 2D de números pseudo-randômicos inteiros
# primeiro argumento continua sendo o intervalo onde se gera os números aleatórios
# deve-se passar um segundo argumento size = ..., onde ... informa o tamanho do array  (constitue uma tupla 2D)
# (3,2) : 3 linhas e 2 colunas
x = random.randint(100, size=(3,2))
print(x)

print()

print('Número aleatório real 2D')
# gerando um array 2D de números pseudo-randômicos inteiros
# primeiro argumento continua sendo o intervalo onde se gera os números aleatórios
# deve-se passar um segundo argumento size = ..., onde ... informa o tamanho do array  (constitue uma tupla 2D)
# (3,2) : 3 linhas e 2 colunas
x = random.rand(3,5)*100       # valor 100 delimita o intervalo
print(x)


número inteiro aleatório:
63
5

número real aleatório:
0.0936047960229176
90.70863387342875

[21 36 58 84 37 49 13 91 43  0]

Número aleatório inteiro 2D
[[71 88]
 [19 40]
 [44 63]]

Número aleatório real 2D
[[52.51936256 97.76735822 74.62604965 69.50233057  0.39898952]
 [93.77005832 76.04492035 68.2867715  78.3127974  35.85322493]
 [77.68378165 89.4122198  89.66577513 33.00021026 26.29328504]]


### função: **random.choice( )**

In [144]:
# Podemos obter um valor aleatório de uma lista a partir da função/método random.choice()
x = random.choice([1,2,3,4,5,6,7])
print('Número aleatório da lista: ',x)

print()

# Passando um segundo argumento para essa função, podemos obter um array dos números sorteados dessa lista.
# O segundo parâmetro corresponde a uma tupla. (Assim podemos gerar diferentes formas)
x = random.choice([1,2,3,4,5,6,7], size = (2,2,5))
print(x)

print()

print('NOVO')
x = random.choice([1,2,3,4,5,6,7], size = (6,3,5))
print(x)

Número aleatório da lista:  3

[[[6 3 4 2 3]
  [4 1 7 5 5]]

 [[7 2 4 7 7]
  [5 3 1 5 3]]]

NOVO
[[[1 4 3 5 6]
  [4 7 5 7 6]
  [2 4 1 3 3]]

 [[3 3 3 3 3]
  [6 2 2 1 2]
  [2 3 7 6 2]]

 [[3 7 1 4 3]
  [6 4 3 5 7]
  [1 6 1 6 4]]

 [[5 4 4 3 3]
  [7 6 4 7 4]
  [2 4 2 6 3]]

 [[1 3 3 7 7]
  [1 6 2 7 1]
  [5 3 3 7 4]]

 [[6 1 6 5 1]
  [6 3 4 6 4]
  [6 7 3 1 3]]]


### Sementes de Números Pseudo-randômicos

A semente aleatória é um número (ou vetor) usado para iniciar o algoritmo gerador de números pseudo-aleatórios.

A escolha de uma boa semente aleatória é crucial quando se trata de segurança da informação e encriptação computacional.

Computacionalmente as sementes aleatórias são muitas vezes geradas a partir de um valor que não se repetirá, como por exemplo, a marca temporal atual

In [11]:
from numpy import random

# iserindo uma determinada semente a mesma sequênncia de números aleatórios vai ser gerada.
random.seed(0)
print(random.randint(10,100, size=(10)))
random.seed(1)
print(random.randint(10,100, size=(10)))


[54 57 74 77 77 19 93 31 46 97]
[47 22 82 19 85 15 89 74 26 11]


## Funções Universais (unfucs)

In [21]:
import numpy as np

# Exemplo 01: somar elementos de duas listas (dois a dois)
x = [1,2,3,4]
y = [4,5,6,7]

z = []

# função zip pega um elemento de x e um elemento de y  (apenas correspondentes a interações)
for i,j in zip(x,y):
  z.append(i+j)

print(z)

print()

# Exemplo 02: somar os elementos de duas listas par a par: via Numpy
# Deve-se usar o método .add()
# O primeiro argumento é uma lista, e o segundo também.

x = [1,2,3,4]
y = [4,5,6,7] 
z = np.add(x,y)            
print(z, type(z))

print()

# Exemplo 03: forma mais simples
# Diferente do operador de concatenação na forma que vimos em listas. 
x = np.array([1,2,3,4])
y = np.array([4,5,6,7]) 
z = x+y            
print(z, type(z))


print()


# Exemplo 04: definindo uma função universal.
# function - nome da função.
# inputs: o número de argumentos de entradas (arrays/listas).
# outputs: o número de arrays de saída.
# observe que a saída será um array da classe universal.

def myadd(x,y):
  return x+y  

myadd2 = np.frompyfunc(myadd,2,1)
print(myadd(x,y))
print(myadd2)

[5, 7, 9, 11]

[ 5  7  9 11] <class 'numpy.ndarray'>

[ 5  7  9 11] <class 'numpy.ndarray'>

[ 5  7  9 11]
<ufunc 'myadd (vectorized)'>
